{
 "title": "SMS App metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Time window", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Classification Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total{exported_endpoint=\"/sms/predict\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles (p50 / p95 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_http_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_request_duration_seconds_bucket[$interval])) by (le)) ",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_http_request_duration_seconds_bucket[$interval])) by (le))\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Total request by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_total[$interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 } }
 ]
}