#!/usr/bin/env bash
set -euo pipefail

# operation/scripts/generate_inventory.sh
# Usage: generate_inventory.sh <CTRL_IP> <WORKER_COUNT>
# Writes inventory.cfg in the current directory containing only active Vagrant machines.

CTRL_IP=${1:-192.168.56.100}
WORKER_COUNT=${2:-2}
OUT_FILE="inventory.cfg"
rm -f "$OUT_FILE"

# helper: write a host line by parsing `vagrant ssh-config` for a machine
write_host_from_sshconfig() {
  local name="$1"

  # vagrant ssh-config returns non-zero when machine is not created/running
  if ! vagrant ssh-config "$name" >/dev/null 2>&1; then
    return 1
  fi

  # Capture ssh-config and parse fields
  local cfg
  cfg=$(mktemp)
  vagrant ssh-config "$name" > "$cfg"

  # Extract fields (first match)
  local host port user key
  host=$(awk '/HostName/ {print $2; exit}' "$cfg" || true)
  port=$(awk '/Port/ {print $2; exit}' "$cfg" || true)
  user=$(awk '/User/ {print $2; exit}' "$cfg" || true)
  key=$(awk '/IdentityFile/ {print $2; exit}' "$cfg" || true)
  rm -f "$cfg"

  # strip surrounding quotes from key if present
  key=${key#"}
  key=${key%"}

  # Write ansible host entry using parsed values
  # include ansible_python_interpreter for Ubuntu 20+/24
  echo "${host} ansible_user=${user:-vagrant} ansible_ssh_private_key_file=${key:-.vagrant/machines/${name}/virtualbox/private_key} ansible_ssh_port=${port:-22} ansible_python_interpreter=/usr/bin/python3" >> "$OUT_FILE"
  return 0
}

# Start writing inventory
echo "# Generated by generate_inventory.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "[ctrl]" >> "$OUT_FILE"
# Try adding ctrl from ssh-config; if that fails, fallback to known IP/key
if ! write_host_from_sshconfig "ctrl"; then
  echo "${CTRL_IP} ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/ctrl/virtualbox/private_key ansible_python_interpreter=/usr/bin/python3" >> "$OUT_FILE"
fi

echo "" >> "$OUT_FILE"
echo "[workers]" >> "$OUT_FILE"
for i in $(seq 1 "$WORKER_COUNT"); do
  name="node-${i}"
  if ! write_host_from_sshconfig "$name"; then
    # machine not created or no ssh-config available; skip writing unless you want fallback
    # fallback: write the static IP/key (uncomment if you prefer unconditional entries)
    ip="192.168.56.$((100 + i))"
    # echo "${ip} ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/${name}/virtualbox/private_key ansible_python_interpreter=/usr/bin/python3" >> "$OUT_FILE"
  fi
done

# Short summary
echo "Wrote $OUT_FILE"
